In [38]:
import tensorflow as tf
import numpy as np
import os
from tensorflow.python.framework import ops  
ops.reset_default_graph()

In [38]:
sess = tf.Session()

In [40]:
x_shape = [1, 4, 4, 1]  
x_val = np.random.uniform(size=x_shape)

In [41]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [42]:
my_filter = tf.constant(0.25, shape=[2, 2, 1, 1])
my_strides = [1, 2, 2, 1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding="SAME", name="Moving_Avg_window")

In [43]:
def custom_layer(input_matrix):
    input_matrix_sqeezed = tf.squeeze(input_matrix)
    print(input_matrix_sqeezed)
    W = tf.constant([[1., 2.], [-1, 3.]])
    b = tf.constant(1., shape=[2, 2])
    temp1 = tf.matmul(W, input_matrix_sqeezed)
    tmp = tf.add(temp1, b)
    z = tf.sigmoid(tmp)
    return z
    
with tf.name_scope('Custom_Layer') as scope:
    custom_layer1 = custom_layer(mov_avg_layer)

Tensor("Custom_Layer/Squeeze:0", shape=(2, 2), dtype=float32)


In [44]:
print(sess.run(mov_avg_layer, feed_dict={x_data: x_val}))
print(mov_avg_layer.shape)

[[[[ 0.47857749]
   [ 0.42941326]]

  [[ 0.67803377]
   [ 0.44940308]]]]
(1, 2, 2, 1)


In [45]:
print(sess.run(custom_layer1, feed_dict={x_data: x_val}))

[[ 0.94451946  0.91118741]
 [ 0.92794377  0.87200409]]


In [46]:
if not os.path.exists('define_layers/'):
    os.mkdir('define_layers/')
writer = tf.summary.FileWriter("define_layers/", sess.graph)